# Generated by Django 4.2.30 on 2026-04-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_pendingregistration'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pendingregistration',
            new_name='users_pendi_email_2ec85b_idx',
            old_name='users_pendi_email_0df1ab_idx',
        ),
        migrations.RenameIndex(
            model_name='pendingregistration',
            new_name='users_pendi_usernam_bc385b_idx',
            old_name='users_pendi_usernam_62e12d_idx',
        ),
        migrations.RenameIndex(
            model_name='pendingregistration',
            new_name='users_pendi_expires_689b96_idx',
            old_name='users_pendi_expires_f9cb12_idx',
        ),
    ]
