# Generated by Django 4.2.30 on 2026-05-05 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_demo_admin'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bugreport',
            new_name='users_bugre_status_193b5e_idx',
            old_name='users_bugre_status_55ef24_idx',
        ),
        migrations.RenameIndex(
            model_name='bugreport',
            new_name='users_bugre_priorit_914ec9_idx',
            old_name='users_bugre_priorit_9cc9bb_idx',
        ),
        migrations.RenameIndex(
            model_name='bugreport',
            new_name='users_bugre_created_24e285_idx',
            old_name='users_bugre_created_5f78ab_idx',
        ),
    ]
