# Generated by Django 4.2.30 on 2026-05-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ares', '0002_sheetshare'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sheetshare',
            new_name='ares_sheets_sheet_i_b3a7cd_idx',
            old_name='ares_sheets_sheet_i_f3065f_idx',
        ),
        migrations.RenameIndex(
            model_name='sheetshare',
            new_name='ares_sheets_user_id_126e26_idx',
            old_name='ares_sheets_user_id_3d8cc8_idx',
        ),
        migrations.RenameIndex(
            model_name='sheetshare',
            new_name='ares_sheets_permiss_004edd_idx',
            old_name='ares_sheets_permiss_b4107f_idx',
        ),
    ]
