# Generated by Django 4.2.30 on 2026-05-12 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ares', '0004_sheetchatmessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sheetchatmessage',
            new_name='ares_sheetc_sheet_i_af74e5_idx',
            old_name='ares_sheetch_sheet_i_3b7b4f_idx',
        ),
        migrations.RenameIndex(
            model_name='sheetchatmessage',
            new_name='ares_sheetc_user_id_cea4eb_idx',
            old_name='ares_sheetch_user_id_425ba8_idx',
        ),
    ]
