# Generated by Django 4.2.30 on 2026-05-27 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ares', '0005_rename_ares_sheetch_sheet_i_3b7b4f_idx_ares_sheetc_sheet_i_af74e5_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField(max_length=800)),
                ('kind', models.CharField(choices=[('script', 'Skrypt'), ('template', 'Szablon'), ('tool', 'Narzędzie'), ('macro', 'Makro')], default='script', max_length=30)),
                ('version', models.CharField(blank=True, default='1.0.0', max_length=40)),
                ('script_body', models.TextField()),
                ('instructions', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('approved', 'Zatwierdzony'), ('rejected', 'Odrzucony')], default='pending', max_length=30)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ares_addons', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ares_addons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='ares_addon_status_c5ba01_idx'), models.Index(fields=['kind'], name='ares_addon_kind_b3c875_idx'), models.Index(fields=['author'], name='ares_addon_author__884424_idx')],
            },
        ),
    ]
