# Generated by Django 4.2.30 on 2026-05-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ares', '0006_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='scripts_data',
            field=models.TextField(default='[]'),
        ),
    ]
