# Generated by Django 4.2.30 on 2026-05-27 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ares', '0008_seed_demo_addons'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=190, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspace_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='ares.workspacegroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_watches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupSheetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_sheet_assignments', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_assignments', to='ares.workspacegroup')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='ares.sheet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ares_friends_friend', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ares_friends_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='ares.workspacegroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['group', 'created_at'],
                'indexes': [models.Index(fields=['group'], name='ares_worksp_group_i_f71d55_idx'), models.Index(fields=['user'], name='ares_worksp_user_id_6d58dd_idx'), models.Index(fields=['role'], name='ares_worksp_role_638814_idx')],
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='workspacegroup',
            index=models.Index(fields=['owner'], name='ares_worksp_owner_i_944877_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacegroup',
            index=models.Index(fields=['slug'], name='ares_worksp_slug_7434fd_idx'),
        ),
        migrations.AddIndex(
            model_name='groupwatch',
            index=models.Index(fields=['group'], name='ares_groupw_group_i_0d6e1f_idx'),
        ),
        migrations.AddIndex(
            model_name='groupwatch',
            index=models.Index(fields=['user'], name='ares_groupw_user_id_d990f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupwatch',
            unique_together={('group', 'user')},
        ),
        migrations.AddIndex(
            model_name='groupsheetassignment',
            index=models.Index(fields=['group'], name='ares_groups_group_i_3ece32_idx'),
        ),
        migrations.AddIndex(
            model_name='groupsheetassignment',
            index=models.Index(fields=['sheet'], name='ares_groups_sheet_i_826319_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupsheetassignment',
            unique_together={('group', 'sheet')},
        ),
        migrations.AddIndex(
            model_name='friendlink',
            index=models.Index(fields=['owner'], name='ares_friend_owner_i_dec02b_idx'),
        ),
        migrations.AddIndex(
            model_name='friendlink',
            index=models.Index(fields=['friend'], name='ares_friend_friend__b05d8a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='friendlink',
            unique_together={('owner', 'friend')},
        ),
    ]
