# Generated by Django 4.2.30 on 2026-06-03 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ares', '0009_workspacegroup_groupwatch_groupsheetassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-installed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('report_type', models.CharField(choices=[('executive', 'Executive'), ('analytical', 'Analytical'), ('dashboard', 'Dashboard'), ('notebook', 'Notebook / Quarto')], default='analytical', max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Prywatny'), ('team', 'Team'), ('organization', 'Organizacja')], default='private', max_length=20)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('snapshot_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=190, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('website', models.URLField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('private', 'Prywatna'), ('internal', 'WewnÄ™trzna'), ('public', 'Publiczna')], default='private', max_length=20)),
                ('allow_member_team_creation', models.BooleanField(default=False)),
                ('settings_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='addon',
            name='auth_mode',
            field=models.CharField(blank=True, default='user', max_length=40),
        ),
        migrations.AddField(
            model_name='addon',
            name='category',
            field=models.CharField(blank=True, default='Automatyzacja', max_length=80),
        ),
        migrations.AddField(
            model_name='addon',
            name='entry_point',
            field=models.CharField(blank=True, default='onOpen', max_length=120),
        ),
        migrations.AddField(
            model_name='addon',
            name='host',
            field=models.CharField(choices=[('sheets', 'Arkusze'), ('reports', 'Raporty'), ('workspace', 'Workspace')], default='sheets', max_length=30),
        ),
        migrations.AddField(
            model_name='addon',
            name='installation_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addon',
            name='menu_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='addon',
            name='scopes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workspacegroup',
            name='notification_setting',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=20),
        ),
        migrations.AddField(
            model_name='workspacegroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ares.workspacegroup'),
        ),
        migrations.AddField(
            model_name='workspacegroup',
            name='settings_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workspacegroup',
            name='specification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workspacegroup',
            name='visibility',
            field=models.CharField(choices=[('visible', 'Visible'), ('secret', 'Secret')], default='visible', max_length=20),
        ),
        migrations.AlterField(
            model_name='workspacegroupmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('maintainer', 'Maintainer'), ('member', 'Member')], default='member', max_length=20),
        ),
        migrations.AddField(
            model_name='workspacegroup',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='ares.workspaceorganization'),
        ),
        migrations.AddIndex(
            model_name='workspacegroup',
            index=models.Index(fields=['organization'], name='ares_worksp_organiz_288dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacegroup',
            index=models.Index(fields=['parent'], name='ares_worksp_parent__46bb2b_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacegroup',
            index=models.Index(fields=['visibility'], name='ares_worksp_visibil_5f57ae_idx'),
        ),
        migrations.AddField(
            model_name='workspaceorganization',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_workspace_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreport',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='ares.workspacegroup'),
        ),
        migrations.AddField(
            model_name='userreport',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='ares.workspaceorganization'),
        ),
        migrations.AddField(
            model_name='userreport',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userreport',
            name='sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='ares.sheet'),
        ),
        migrations.AddField(
            model_name='addoninstallation',
            name='addon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='ares.addon'),
        ),
        migrations.AddField(
            model_name='addoninstallation',
            name='sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addon_installations', to='ares.sheet'),
        ),
        migrations.AddField(
            model_name='addoninstallation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_installations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='workspaceorganization',
            index=models.Index(fields=['owner'], name='ares_worksp_owner_i_d56d83_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceorganization',
            index=models.Index(fields=['slug'], name='ares_worksp_slug_dcc08e_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceorganization',
            index=models.Index(fields=['visibility'], name='ares_worksp_visibil_4f2256_idx'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['owner', 'updated_at'], name='ares_userre_owner_i_10412f_idx'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['report_type'], name='ares_userre_report__7f8520_idx'),
        ),
        migrations.AddIndex(
            model_name='userreport',
            index=models.Index(fields=['visibility'], name='ares_userre_visibil_7a0e08_idx'),
        ),
        migrations.AddIndex(
            model_name='addoninstallation',
            index=models.Index(fields=['addon'], name='ares_addoni_addon_i_c4628b_idx'),
        ),
        migrations.AddIndex(
            model_name='addoninstallation',
            index=models.Index(fields=['user'], name='ares_addoni_user_id_d03a55_idx'),
        ),
        migrations.AddIndex(
            model_name='addoninstallation',
            index=models.Index(fields=['sheet'], name='ares_addoni_sheet_i_790c1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='addoninstallation',
            unique_together={('addon', 'user', 'sheet')},
        ),
    ]
