services:
  - type: web
    name: ares
    env: python
    buildCommand: ./build.sh
    startCommand: uv run gunicorn projekt_baza.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ares-db
          property: connectionString
      - key: DATABASE_SSL_REQUIRE
        value: "True"
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.smtp.EmailBackend
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false

databases:
  - name: ares-db
    databaseName: ares
    user: ares
